import { activeScene, type AppState } from '../state/AppState.ts'
import { MAX_SCENE_OBJECTS, remainingCapacity, singleSelectedObject } from '../state/sceneActions.ts'
import type { CatalogueAvailability } from '../state/catalogueWorkspaceState.ts'
import { text } from '../i18n/index.ts'
import { inspectorSourceLabel } from './shellWording.ts'
export interface ShellModel { readonly mode: AppState['activeMode']; readonly modeButtons: readonly { readonly mode: AppState['activeMode']; readonly label: string; readonly pressed: boolean }[]; readonly leftDrawer: { readonly open: boolean; readonly content: AppState['activeMode']; readonly toggleLabel: string }; readonly inspector: { readonly open: boolean; readonly content: 'empty' | 'single' | 'multiple'; readonly selectedCount: number; readonly identity: { readonly name: string; readonly sourceLabel: string } | null; readonly toggleLabel: string }; readonly timeDrawer: { readonly open: boolean }; readonly viewDrawer: { readonly open: boolean; readonly mapOpen: boolean; readonly mapMaximized: boolean }; readonly sheetOpen: boolean; readonly sensorSettingsHost: 'inspector'; readonly orbitLab: { readonly tab: AppState['orbitLab']['authoring']['drawerTab']; readonly edit: 'none' | 'single' | 'multiple'; readonly editMessage: string; readonly showEmptyState: boolean; readonly createOrbitEnabled: boolean; readonly objectCountLabel: string; readonly limitMessage: string }; readonly realObjects: { readonly showEmptyState: boolean; readonly objectCountLabel: string; readonly catalogueLine: string; readonly addRecordEnabled: boolean }; readonly catalogueWorkspace: { readonly available: boolean; readonly open: boolean; readonly addDisabled: boolean } }
export function buildShellModel(input: { readonly state: AppState; readonly shell: import('../state/shellState.ts').ShellState; readonly catalogue: CatalogueAvailability; readonly loading: boolean }): ShellModel {
  const t = text().shell; const { state, shell, catalogue, loading } = input; const active = activeScene(state); const orbitLab = state.orbitLab.scene; const real = state.realObjects.scene; const single = singleSelectedObject(active); const selectedCount = active.selection.ids.length; const availability = catalogue.kind === 'not-loaded' ? t.catalogueNotLoaded : catalogue.kind === 'loading' ? t.catalogueLoading : catalogue.kind === 'ready' ? t.catalogueLoaded(catalogue.entryCount) : catalogue.snapshotId ? t.catalogueRefreshFailed : t.catalogueUnavailable
  return { mode: state.activeMode, modeButtons: (['orbitLab', 'realObjects'] as const).map((mode) => ({ mode, label: t.modes[mode], pressed: state.activeMode === mode })), leftDrawer: { open: shell.leftDrawerOpen, content: state.activeMode, toggleLabel: shell.leftDrawerOpen ? t.collapseWorkspace : t.expandWorkspace }, inspector: { open: shell.inspectorOpen, content: selectedCount === 0 ? 'empty' : selectedCount === 1 ? 'single' : 'multiple', selectedCount, identity: single ? { name: single.name, sourceLabel: inspectorSourceLabel(single) } : null, toggleLabel: shell.inspectorOpen ? t.collapseInspector : t.expandInspector }, timeDrawer: { open: shell.timeDrawerOpen }, viewDrawer: { open: shell.viewDrawerOpen, mapOpen: state.view.groundTrackMapVisible, mapMaximized: state.view.groundTrackMapVisible && shell.mapMaximized }, sheetOpen: shell.narrowViewport && (shell.leftDrawerOpen || shell.inspectorOpen), sensorSettingsHost: 'inspector', orbitLab: { tab: state.orbitLab.authoring.drawerTab, edit: state.orbitLab.scene.selection.ids.length === 0 ? 'none' : state.orbitLab.scene.selection.ids.length === 1 ? 'single' : 'multiple', editMessage: state.orbitLab.scene.selection.ids.length === 0 ? t.editOrbitNoSelection : state.orbitLab.scene.selection.ids.length === 1 ? '' : t.editOrbitMultiple, showEmptyState: orbitLab.objects.length === 0, createOrbitEnabled: !loading && remainingCapacity(orbitLab) > 0, objectCountLabel: t.objectCount(orbitLab.objects.length, MAX_SCENE_OBJECTS), limitMessage: orbitLab.objects.length >= MAX_SCENE_OBJECTS ? t.sceneLimit(MAX_SCENE_OBJECTS) : '' }, realObjects: { showEmptyState: real.objects.length === 0, objectCountLabel: t.objectCount(real.objects.length, MAX_SCENE_OBJECTS), catalogueLine: availability, addRecordEnabled: !loading && remainingCapacity(real) > 0 }, catalogueWorkspace: { available: state.activeMode === 'realObjects', open: state.activeMode === 'realObjects' && shell.catalogueWorkspaceOpen, addDisabled: remainingCapacity(real) === 0 } }
}
