import type { OrbitalObject } from '../simulation/OrbitalObject.ts'
import { parseOmmRecord } from '../data/omm.ts'
import { parseTle } from '../data/tle.ts'
import type { SceneDocumentV1, RealObjectV1 } from '../data/sceneDocument.ts'
import { EMPTY_SCENE, type ProductMode, type SceneState } from '../state/AppState.ts'
import { addObjects, MAX_SCENE_OBJECTS, setSelection } from '../state/sceneActions.ts'
import { sceneObjectFromCatalogueRecord } from './catalogueToScene.ts'
import { applyLayerBudgetsInOrder, type BudgetedLayer } from '../state/sceneComplexity.ts'
import type { ResolvedCatalogueRecords } from './CatalogueController.ts'

export type SceneResolutionProblem = { readonly kind: 'catalogue-missing'; readonly id: string; readonly catalogId: string } | { readonly kind: 'element-set-changed'; readonly id: string; readonly catalogId: string; readonly savedEpochUnixSeconds: number; readonly currentEpochUnixSeconds: number } | { readonly kind: 'source-invalid'; readonly id: string; readonly message: string } | { readonly kind: 'scene-capacity'; readonly mode: ProductMode; readonly droppedIds: readonly string[] } | { readonly kind: 'layer-budget'; readonly mode: ProductMode; readonly layer: BudgetedLayer; readonly budget: number; readonly changedIds: readonly string[] }
export interface ResolvedSceneDocument { readonly activeMode: ProductMode; readonly orbitLab: SceneState; readonly realObjects: SceneState; readonly simulation: SceneDocumentV1['simulation']; readonly view: SceneDocumentV1['view']; readonly problems: readonly SceneResolutionProblem[] }
export interface SceneResolutionDependencies { loadCatalogue(): Promise<void>; resolveRecords(catalogIds: readonly string[]): Promise<ResolvedCatalogueRecords> }

function presentation(object: RealObjectV1, built: OrbitalObject): OrbitalObject { return { ...built, id: object.id, style: { ...object.style }, sensor: { ...object.sensor }, reachConstraint: { ...object.reachConstraint }, display: { ...object.display } } }
function manualTle(object: Extract<RealObjectV1, { kind: 'tle' }>): { object?: OrbitalObject; problem?: SceneResolutionProblem } { const input = object.name === null ? `${object.line1}\n${object.line2}` : `0 ${object.name}\n${object.line1}\n${object.line2}`; const parsed = parseTle(input); if (!parsed.ok) return { problem: { kind: 'source-invalid', id: object.id, message: parsed.errors.map((error) => error.message).join(' ') } }; return { object: { id: object.id, name: parsed.definition.name ?? `NORAD ${parsed.definition.catalogId}`, source: { kind: 'tle', definition: parsed.definition }, propagation: { kind: 'sgp4' }, editingLock: { kind: 'none' }, style: { ...object.style }, sensor: { ...object.sensor }, reachConstraint: { ...object.reachConstraint }, display: { ...object.display } } } }
function manualOmm(object: Extract<RealObjectV1, { kind: 'omm' }>): { object?: OrbitalObject; problem?: SceneResolutionProblem } { const parsed = parseOmmRecord(object.record, { kind: 'manual' }); if (!parsed.ok) return { problem: { kind: 'source-invalid', id: object.id, message: parsed.errors.map((error) => error.message).join(' ') } }; return { object: { id: object.id, name: parsed.definition.name, source: { kind: 'omm', definition: parsed.definition }, propagation: { kind: 'sgp4' }, editingLock: { kind: 'none' }, style: { ...object.style }, sensor: { ...object.sensor }, reachConstraint: { ...object.reachConstraint }, display: { ...object.display } } } }

export async function resolveSceneDocument(document: SceneDocumentV1, deps: SceneResolutionDependencies): Promise<ResolvedSceneDocument> {
  const problems: SceneResolutionProblem[] = []; const records = new Map<string, OrbitalObject>(); const refs = document.realObjects.objects.filter((object): object is Extract<RealObjectV1, { kind: 'catalogue' }> => object.kind === 'catalogue')
  if (refs.length > 0) { await deps.loadCatalogue(); const resolved = await deps.resolveRecords([...new Set(refs.map((object) => object.catalogId))]); for (const ref of refs) { if (resolved.missingIds.includes(ref.catalogId)) { problems.push({ kind: 'catalogue-missing', id: ref.id, catalogId: ref.catalogId }); continue }; const record = resolved.records.find((candidate) => candidate.NORAD_CAT_ID === ref.catalogId); if (!record) { problems.push({ kind: 'catalogue-missing', id: ref.id, catalogId: ref.catalogId }); continue }; const built = sceneObjectFromCatalogueRecord(record, resolved.manifest, ref.style.colorHex); if (!built.ok) { problems.push({ kind: 'source-invalid', id: ref.id, message: built.message }); continue }; records.set(ref.id, presentation(ref, built.object)); if (record.EPOCH && Date.parse(record.EPOCH) / 1000 !== ref.savedEpochUnixSeconds) problems.push({ kind: 'element-set-changed', id: ref.id, catalogId: ref.catalogId, savedEpochUnixSeconds: ref.savedEpochUnixSeconds, currentEpochUnixSeconds: Date.parse(record.EPOCH) / 1000 }) } }
  const orbitObjects: OrbitalObject[] = []; for (const object of document.orbitLab.objects) { orbitObjects.push({ id: object.id, name: object.name, source: { kind: 'keplerian', geometry: { ...object.geometry }, phase: { referenceInstant: { unixSeconds: object.phase.referenceUnixSeconds }, meanAnomalyAtReferenceRad: object.phase.meanAnomalyAtReferenceRad } }, propagation: { kind: object.propagation }, editingLock: { kind: object.editingLock }, style: { ...object.style }, sensor: { ...object.sensor }, reachConstraint: { ...object.reachConstraint }, display: { ...object.display }, ...(object.notes === null ? {} : { notes: object.notes }) }) }
  const realObjects: OrbitalObject[] = []; for (const object of document.realObjects.objects) { if (object.kind === 'catalogue') { const resolved = records.get(object.id); if (resolved) realObjects.push(resolved) } else { const result = object.kind === 'tle' ? manualTle(object) : manualOmm(object); if (result.object) realObjects.push(result.object); else if (result.problem) problems.push(result.problem) } }
  function buildScene(objects: readonly OrbitalObject[], savedIds: readonly string[], primaryId: string | null, mode: ProductMode): SceneState { const capped = objects.slice(0, MAX_SCENE_OBJECTS); if (objects.length > MAX_SCENE_OBJECTS) problems.push({ kind: 'scene-capacity', mode, droppedIds: objects.slice(MAX_SCENE_OBJECTS).map((object) => object.id) }); const budgeted = applyLayerBudgetsInOrder(capped); for (const trim of budgeted.trimmed) problems.push({ kind: 'layer-budget', mode, layer: trim.layer, budget: trim.budget, changedIds: trim.ids }); const kept = budgeted.objects; const base = kept.length === 0 ? EMPTY_SCENE : addObjects(EMPTY_SCENE, kept); return setSelection(base, { ids: savedIds, primaryId }) }
  return { activeMode: document.activeMode, orbitLab: buildScene(orbitObjects, document.orbitLab.selectedIds, document.orbitLab.primaryId, 'orbitLab'), realObjects: buildScene(realObjects, document.realObjects.selectedIds, document.realObjects.primaryId, 'realObjects'), simulation: document.simulation, view: document.view, problems }
}
